= Rest docs demo
zaccoding;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Get resources

| `POST`
| Save resources

| `PUT`
| Update resources

| `DELETE`
| Delete resources
|===

[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[resources-person-save]]
=== Save person

`POST` Save person

operation::save-person[snippets='request-fields,request-body,response-fields,curl-request,http-response']

[[resources-person-update]]
=== Update person

`PUT` Update person

operation::update-person[snippets='path-parameters,request-fields,request-body,response-fields,curl-request,http-response']

[[resources-person-delete]]
=== Delete person

`DELETE` Delete person

operation::delete-person[snippets='path-parameters,request-fields,request-body,response-fields,curl-request,http-response']



[[resources-person-get]]
=== Get person

`GET` Search one person

operation::get-person[snippets='path-parameters,request-fields,request-body,response-fields,curl-request,http-response']

[[resources-persons-get]]
=== Get persons

`GET` Search persons

operation::get-persons[snippets='request-parameters,request-body,response-fields,curl-request,http-response']

